import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";

import { ProductsProvider } from "./context/ProductsProvider";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { UserProductsProvider } from "./context/UserProductsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={inter.className}>
        <ProductsProvider>
          <UserProductsProvider>
            <Header />
            <AuthProvider>{children}</AuthProvider>
            <Footer />
          </UserProductsProvider>
        </ProductsProvider>
      </body>
    </html>
  );
}
